config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get '/about', to: "about#index"
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :password_resets
  resource :passwords

  get '/auth/twitter2/callback', to: 'omniauth_callbacks#twitter2'

  resources :twitter_accounts, only: [:index, :destroy] do
    resources :tweets, except: [:show]
    get '/my_tweets', to: "tweets#my_tweets"
  end

  # get '/twitter_accounts/:twitter_account_id/my_tweets', to: "tweets#my_tweets"
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :set_user_by_token, only: [:edit, :update]

  def new
  end

  def create
    if (user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        # if rails 7.1 token: user.generate_token_for(:password_reset)
        token: create_token({ user_id: user.id })
      ).password_reset.deliver_later
    end

    flash[:notice] = "If the email is on record we will send an email"
    redirect_to root_path
  end

  def edit
  end

  def update
    if @user.update(password_params)
      flash[:notice] = "Your password has been reset successfully, please log in."
      redirect_to new_sessions_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private 

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def set_user_by_token
    # if rails 7.1 @user = User.find_by_token_for(:password_reset, params[:token])
    @user = User.find_by(id: decode_token(params[:token])["user_id"])

    unless @user.present?
      flash[:alert] = "Invalid/expired token, please try again."
      redirect_to new_password_resets_path
    end
  end
end

app/views/password_resets/edit.html.erb
<header>
  <h1>Edit Your Password</h1>
</header>
<main>
  <%= form_with model: @user, url: password_resets_path({token: params[:token]}) do |f| %>
    <%= render "shared/form_errors", f: f %>

    <div class="mb-3">
      <%= f.label :password, "password", class: "form-label" %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :password_confirmation, "password confirmation", class: "form-label" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
      <%= f.submit "Update Password", class: "btn btn-primary" %>
    <% end %>
</main>

app/views/password_resets/new.html.erb
<header>
  <h1>Send Reset Email</h1>
</header>
<main>
  <%= form_with url: password_resets_path, method: :post do |f| %>
    <div class="mb-3">
      <%= f.label :email, "email", class: "form-label" %>
      <%= f.text_field :email, class: "form-control", placeholder: "example@mail.com" %>
    </div>
      <%= f.submit "Reset", class: "btn btn-primary" %>
  <% end %>
</main>