config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get '/about', to: "about#index"
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :password_resets
  resource :passwords

  get '/auth/twitter2/callback', to: 'omniauth_callbacks#twitter2'

  resources :twitter_accounts, only: [:index, :destroy] do
    resources :tweets, except: [:show]
    get '/my_tweets', to: "tweets#my_tweets"
  end

  # get '/twitter_accounts/:twitter_account_id/my_tweets', to: "tweets#my_tweets"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account

  validates :body, length: { minimum: 1, maximum: 280 }
  validates :publish_at, presence: true

  after_initialize do
    self.publish_at ||= 24.hour.from_now
  end

  def published?
    tweet_id?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    twitter_account = current_user.twitter_accounts.find(params[:twitter_account_id])
    TwitterFacade.get_tweets(current_user, twitter_account)
    # current_user.twitter_accounts.find(params[:twitter_account_id]).tweets
  end

  def my_tweets
    @tweets = current_user.twitter_accounts.find(params[:twitter_account_id]).tweets
  end

  def new
    @tweet = current_user.twitter_accounts.find(params[:twitter_account_id]).tweets.new()
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update(tweet_params)
      flash[:notice] = "Tweet has been successfully updated"
      redirect_to twitter_account_my_tweets_path(current_user.twitter_accounts.find(params[:twitter_account_id]))
    else
      render :edit, status: :unprocessable_entity
    end 
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    @tweet.twitter_account_id = params[:twitter_account_id]

    if @tweet.save
      flash[:notice] = "successfully scheduled the tweet!"
      redirect_to twitter_account_my_tweets_path(current_user.twitter_accounts.find(params[:twitter_account_id]))
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    Tweet.find(params[:id]).destroy
    flash[:notice] = "Successfully deleted tweet"
    redirect_to twitter_account_my_tweets_path(current_user.twitter_accounts.find(params[:twitter_account_id]))
  end

  private

  def tweet_params
    params.require(:tweet).permit(:body, :publish_at)
  end
end

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= form_with model: @tweet, url: twitter_account_tweet_path(@tweet.twitter_account, @tweet), method: :patch do |f| %>
  <%= render "shared/form_errors", f: f %>

  <div class="mb-3 mt-3">
    <%= f.label :body, class: "form-label" %>
    <%= f.text_area :body, class: "form-control", placeholder: "Enter in the text of your tweet." %>
  </div>
    <%= f.label :publish_at, class: "form-label" %>
    <%= f.datetime_local_field :publish_at, class: "form-control" %>
  <div>
  <div>
    <%= f.submit "Update", class: "btn btn-primary mb-3 mt-3" %>
  <div>
<% end %>

app/views/tweets/index.html.erb
<h1>Tweets</h1>

app/views/tweets/my_tweets.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>My Tweets</h1>
</div>

  <% @tweets.each do |tweet| %>
    <article class="card w-50 p-3 mb-3 mt-3 text-bg-light">
      <div class="card-body">
        <% if tweet.published? %>
          <h4 class="card-title">Published</h4>
        <% else %>
          <h4 class="card-title">Not Published</h4>
        <% end %>  
      
        <h5 class="card-title">Body</h5>
        <p class="card-text"><%= tweet.body %></h2>

        <h5>Schedule Time</h5>
        <p class="card-text"><%= l tweet.publish_at, format: :long %></p>

        <% if !tweet.published? %>
          <div class="d-flex">
            <%= link_to "Edit", edit_twitter_account_tweet_path(tweet.twitter_account, tweet), style: "margin-right: 0.5rem", class: "btn btn-primary" %>
            <%= button_to "Delete", twitter_account_tweet_path(tweet.twitter_account, tweet), method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger ml-2" %>
          </div>
        <% end %>
      </div>
    </article>
  <% end %>

app/views/tweets/new.html.erb
<h1>Schedule a Tweet for <%= link_to "@#{@tweet.twitter_account.username}", "https://x.com/#{@tweet.twitter_account.username}", target: :_blank %></h1>

<%= form_with model: @tweet, url: twitter_account_tweets_path(@tweet.twitter_account) do |f| %>
  <%= render "shared/form_errors", f: f %>

  <div class="mb-3 mt-3">
    <%= f.label :body, class: "form-label" %>
    <%= f.text_area :body, class: "form-control", placeholder: "Enter in the text of your tweet." %>
  </div>
    <%= f.label :publish_at, class: "form-label" %>
    <%= f.datetime_local_field :publish_at, class: "form-control" %>
  <div>
  <div>
    <%= f.submit "Schedule", class: "btn btn-primary mb-3 mt-3" %>
  <div>
<% end %>