config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get '/about', to: "about#index"
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :password_resets
  resource :passwords

  get '/auth/twitter2/callback', to: 'omniauth_callbacks#twitter2'

  resources :twitter_accounts, only: [:index, :destroy] do
    resources :tweets, except: [:show]
    get '/my_tweets', to: "tweets#my_tweets"
  end

  # get '/twitter_accounts/:twitter_account_id/my_tweets', to: "tweets#my_tweets"
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user
  has_many :tweets

  validates :username, uniqueness: true
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = current_user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy

    flash[:notice] = "Account has been successfully removed"
    redirect_to twitter_accounts_path
  end

  private

  def set_twitter_account
    @twitter_account = current_user.twitter_accounts.find(params[:id])
  end
end

app/views/twitter_accounts/index.html.erb
<div class="d-flex align-items-center justify-content-between">
  <h1>Twitter Accounts</h1>
  <%= link_to "Connect Twitter Account", "/auth/twitter2", method: :post, class: "btn btn-primary" %>
</div>

<% @twitter_accounts.each do |account| %>
  <article class="d-flex align-items-center mb-4 mt-4">
    <div class="me-4">
      <%= image_tag account.image, class: "rounded-circle" %>
      <%= link_to "@#{account.name}", "https://x.com/#{account.username}", target: :_blank %>
    </div>

    <%= link_to "View Tweets", twitter_account_tweets_path(account), class: "btn btn-primary mx-1" %>
    <%= link_to "Schedule a Tweet", new_twitter_account_tweet_path(account), class: "btn btn-primary" %>
    <%= button_to "Disconnect", account, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger mx-1" %>
  </article>
<% end %>