config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get '/about', to: "about#index"
  
  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :password_resets
  resource :passwords

  get '/auth/twitter2/callback', to: 'omniauth_callbacks#twitter2'

  resources :twitter_accounts, only: [:index, :destroy] do
    resources :tweets, except: [:show]
    get '/my_tweets', to: "tweets#my_tweets"
  end

  # get '/twitter_accounts/:twitter_account_id/my_tweets', to: "tweets#my_tweets"
end

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <% f.object.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Scheduled Tweets", about_path, class: "navbar-brand" %>
    <%# <a class="navbar-brand" href="/about">Scheduled Tweets</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
          <%# <a class="nav-link active" aria-current="page" href="/">Home</a> %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Password", edit_passwords_path, class: "nav-link active" %>
          </li>
          <li>
            <%= button_to "Log Out", sessions_path, method: :delete, class: "btn btn-outline-primary", type: "button" %>
          </li>
        <% else %>
          <%= link_to "Sign Up", new_registrations_path, class: "nav-link active" %>
          <%= link_to "Sign In", new_sessions_path, class: "nav-link active" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>